AWSTemplateFormatVersion: "2010-09-09"
Description: Application specific secrets.

Parameters:
  SftpHost:
    NoEcho: true
    Type: String
  SftpUser:
    NoEcho: true
    Type: String
  SftpPassword:
    NoEcho: true
    Type: String
  SftpDestFolder:
    NoEcho: true
    Type: String
  GraphQLHost:
    Type: String
  GraphQLAccessKey:
    NoEcho: true
    Type: String
  GithubToken:
    NoEcho: true
    Type: String

Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BailiffSecret
      Description: This secrets contains SFTP credentials, GraphQL host, and GraphQL access key.
      SecretString: !Sub |
          {"sftp-user":"${SftpHost}",
           "sftp-password":"${SftpUser}",
           "sftp-host":"${SftpPassword}",
           "sftp-dest-folder":"${SftpDestFolder}",
           "graphql-host":"${GraphQLHost}",
           "graphql-access-key":"${GraphQLAccessKey}",
           "github-token":"${GithubToken}"}
      Tags:
        - Key: AppName
          Value: court-bailiff
