AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HelloWorld Application

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: hello.lambda_handler 
      Runtime: ruby3.2
      Architectures:
      - x86_64
      MemorySize: 1024
      Timeout: 20
